import React from 'react';
import { WordList } from '../types';

interface PrintLayoutProps {
  list: WordList;
}

const WORDS_PER_PAGE = 29;

const TableHeader: React.FC = () => (
  <thead>
    <tr className="bg-white">
      <th className="border border-black py-2 px-2 text-center text-sm font-bold w-[25%] font-serif-sc text-black">英文</th>
      <th className="border border-black py-2 px-2 text-center text-sm font-bold w-[20%] font-serif-sc text-black">音标</th>
      <th className="border border-black py-2 px-2 text-center text-sm font-bold w-[25%] font-serif-sc text-black">中文</th>
      <th className="border border-black py-2 px-2 text-center text-sm font-bold w-[30%] font-serif-sc text-black">默写</th>
    </tr>
  </thead>
);

const TableRow: React.FC<{ word: WordPair; index: number }> = ({ word, index }) => (
  <tr key={word.id} className="page-break-inside-avoid">
    {/* English Column */}
    <td className="border border-black p-1 align-middle text-black">
      <div className="flex items-baseline gap-1">
        <span className="text-xs font-mono">{index + 1}.</span>
        <span className="font-medium text-sm">{word.english}</span>
      </div>
    </td>

    {/* Phonetic Column */}
    <td className="border border-black p-1 align-middle text-center text-xs font-sans text-black">
      {word.phonetic ? `[${word.phonetic}]` : ''}
    </td>

    {/* Chinese Column */}
    <td className="border border-black p-1 align-middle font-serif-sc text-sm text-black">
      {word.chinese}
    </td>

    {/* Dictation Column */}
    <td className="border border-black p-0.5 align-middle relative h-7">
      <span className="absolute top-1 left-1 text-xs font-mono text-gray-500">{index + 1}.</span>
    </td>
  </tr>
);

export const PrintLayout: React.FC<PrintLayoutProps> = ({ list }) => {
  const dateObj = new Date(list.createdAt);
  const dateStr = `${dateObj.getFullYear()}年${dateObj.getMonth() + 1}月${dateObj.getDate()}日`;

  // Split words into pages
  const pages: WordPair[][] = [];
  for (let i = 0; i < list.words.length; i += WORDS_PER_PAGE) {
    pages.push(list.words.slice(i, i + WORDS_PER_PAGE));
  }

  if (pages.length === 0) {
    pages.push([]);
  }

  return (
    <div id="print-layout" className="print-only">
      {pages.map((pageWords, pageIndex) => (
        <div
          key={pageIndex}
          className="w-full max-w-[210mm] mx-auto p-8 bg-white text-black page-break-after-always"
        >
          {/* Header Info */}
          <div className="flex justify-between mb-2 font-serif-sc text-sm text-black">
            <span className="font-bold">{list.title}</span>
            <span>日期: {dateStr}</span>
          </div>

          {/* Main Table - Grid Style matching reference */}
          <div className="w-full border-2 border-black">
            <table className="w-full border-collapse">
              <TableHeader />
              <tbody>
                {pageWords.map((word, index) => (
                  <TableRow
                    key={word.id}
                    word={word}
                    index={pageIndex * WORDS_PER_PAGE + index}
                  />
                ))}
                {/* Fill empty rows if needed for consistent page layout */}
                {pageWords.length < WORDS_PER_PAGE &&
                  Array.from({ length: WORDS_PER_PAGE - pageWords.length }).map((_, i) => (
                    <tr key={`empty-${i}`} className="page-break-inside-avoid">
                      <td className="border border-black p-1 align-middle text-black">&nbsp;</td>
                      <td className="border border-black p-1 align-middle text-black">&nbsp;</td>
                      <td className="border border-black p-1 align-middle text-black">&nbsp;</td>
                      <td className="border border-black p-0.5 align-middle h-7">&nbsp;</td>
                    </tr>
                  ))}
              </tbody>
            </table>
          </div>

          {/* Footer */}
          <div className="mt-4 text-center text-xs text-gray-400 font-sans">
            Generated by VocabSmith - Page {pageIndex + 1} of {pages.length}
          </div>
        </div>
      ))}
    </div>
  );
};